### ISSUE TITLE
Create KI lesson structures + authoring

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE#2198] opened 2020-02-06 19:36 UTC
For Feb 22 workshop

Specifications
https://docs.google.com/document/d/1tPAECMEu15xh8N9ZLGe0dZ_QMNqWvva9e3mg_1DHxkw/edit

**Comment by breity** [comment] 2020-02-11 23:13
Duplicate of #2203

**Closed by breity** 2020-02-11 23:13 UTC
Labels: 64 points
